FROM stanfordhpds/r-renv-ssh:latest

# The ONBUILD instructions in r-renv-ssh will:
# 1. Copy renv.lock, renv/activate.R, .Rprofile
# 2. Install the R version specified in renv.lock
# 3. Restore all packages
# 4. Copy the rest of the project files